ramnes/awesome-mongodb

README.md

Added section to list tutorials for making apps that use MongoDB in their stack. Added one tutorial for creating a TV tracker app that uses
MongoDB.

Add Tutorials Section + tutorial

---

README.md

Datadog recently released a few guides on monitoring MongoDB that seemed like they might be a fit here.

add datadog's mongodb guide

---

README.md

add mongobooster to GUI section.
Disclaimer , I am a developer of mongobooster.

Add mongobooster

---

README.md

I would like to add the Mongoeye tool.

Mongoeye schema and data analyzer

---

README.md

Added the `mongo-monitor` tool.

Add 'mongo-monitor'

---

README.md

Feel free to make any changes to my PR. Thanks for considering.

Add examples to `Book` and `Applications` sections

---

README.md

This PR adds a new article resource and puts it in the alphabetical order inside the articles heading. 
- [A Custom WordPress Dashboard with MongoDB Atlas, Microsoft Azure, & Serverless Functions](https://ahmadawais.com/wordpress-mongodb-atlas-microsoft-azure-serverless-functions/) - MongoDB WordPress + Azure FTW!
Thanks for the awesome repo!

📦 NEW: Article about MongoDB

---

README.md

Nosqlclient GitHub link: https://github.com/nosqlclient/nosqlclient

Add Nosqlclient

---

README.md

Hi! 
We've launched free MongoDB online playground. I hope you don't mind adding it to your list!

Add play.db-ai.co — online MongoDB playground

---

README.md

* Added PHPMongo ODM
* Added PHPMongo Migrator

Add PHPMongo tools

---

README.md

This is a great book. This helped me apply good practices in MongoDB.

Add book: " 50 Tips and Tricks for MongoDB Developers"

---

README.md

Hi,
Beanie is an Asynchronous Python ODM for MongoDB.
The documentation could be found here - https://roman-right.github.io/beanie/
Also, there are some articles about Beanie:
- In MongoDB developer blog - https://developer.mongodb.com/article/beanie-odm-fastapi-cocktails/
- Mine from dev.to - https://dev.to/romanright/announcing-beanie-mongodb-odm-56e
I think this fits well to be listed here :smiley:

Add Beanie

---

README.md

I felt this could have gone in a few different sections, but this one seemed most "official MongoDB" 😄

Add developer.mongodb.com

---

README.md

Just added a link to the MongoDB VS Code Extension

Added MongoDB VS Code Extension

---

README.md

This article describes some of the techniques and MongoDB Cloud features we used to debug performance issues and expose sub-optimal queries.

Add article on performance

---

README.md

Hi! I updated the README.md file with two new tools.
[ProvenDB](https://www.provendb.com/) - Data integrity Tool &
[Mingo.io](https://mingo.io/) - MongoDB GUI admin ([Compass alternative](https://mingo.io/compass-alternative)).
Thanks!

Add ProvenDB and Mingo.io to Tools section.

---

README.md

Add AtlasQ - text search in mongo as MongoEngine syntax 
Add flask MongoEngine

Add AtlasQ + flask-MongoEngine

---

README.md

More details here: https://github.com/neuledge/engine-js

Add Neuledge under Javascript

---

README.md

Hi,
[Ballerina](https://ballerina.io) is a modern programming language for integration. Ballerina has an [official MongoDB connector](https://central.ballerina.io/ballerinax/mongodb/latest) developed and maintained by the Ballerina community and the Ballerina team. We would like to include the official Ballerina connector in the awesome MongoDB list and sending this PR to do the same. I am part of the team that develops the Ballerina language and am currently the maintainer of the Ballerina MongoDB connector. Please let me know if I need to do anything more.
Thanks in advance.

Add Official Ballerina Driver to the List

---

README.md

Hi,
Stjepan here from Manning. I thought this title might be a good match for your list. Thank you for considering it.
Best,

Added MongoDB in Action, Third Edition

---

README.md

[BookCars](https://github.com/aelassas/bookcars) is an open-source, cross-platform, highly customizable, scalable, and cost-efficient solution for car rental businesses.

Add BookCars to applications
